# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload_build.outputs.artifact-name }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'
        cache: false

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o myapp-linux -v ./ 

    - name: Test
      run: go test -v ./... --json > test-results.json

    - name: Upload build artifact
      id: upload_build
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: myapp-linux

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.json

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build-artifact,test-results.json
          tag: ${{ github.ref_name }}
          allowUpdates: true
          body: Automatically generated release for tag ${{ github.ref_name }}